CREATE TABLE VEHICULO(
	ID INT IDENTITY(1,1),
	Patente NVARCHAR(8),
	IdMarca INT,
	Modelo NVARCHAR(500),
	Puertas INT,
	TItular NVARCHAR(200),
	CONSTRAINT PK_VEHICULO PRIMARY KEY(ID),
	CONSTRAINT FK_VEHICULO_MARCA FOREIGN KEY (IdMarca) REFERENCES MARCA(ID)
)